---
addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

script:
  - ./bin/test upsert
  - ./bin/test delete

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin;
    docker build -t myobplatform/ansible-runner:$TRAVIS_TAG .;
    docker push myobplatform/ansible-runner:$TRAVIS_TAG;
    docker build -t myobplatform/ansible-runner:latest .;
    docker push myobplatform/ansible-runner:latest;
    fi
