---
- name: "Get tasks directory from environment variable"
  set_fact:
    tasks_dir: "{{ lookup('env','TASKS_DIR') | default('/app', true) }}"

- name: "Validating task dir is valid"
  assert:
    that:
      - "'{{ tasks_dir }}' is directory"
      - "'{{ tasks_dir }}/upsert.yml' is exists"
      - "'{{ tasks_dir }}/delete.yml' is exists"
    msg: "Validating passed"

- include: "{{ tasks_dir }}/upsert.yml"
  when: "k8s_resource is defined and delete_timestamp is not defined"

- include: "{{ tasks_dir }}/delete.yml"
  when: "k8s_resource is not defined or delete_timestamp is defined"
