---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: set resource variables
      set_fact:
        obj_kind: "{{ lookup('env','SHOP_KIND') }}"
        obj_name: "{{ lookup('env','SHOP_OBJECT_NAME') }}"
        obj_namespace: "{{ lookup('env','SHOP_OBJECT_NAMESPACE') }}"
        obj_api_version: "{{ lookup('env','SHOP_API_VERSION') }}"
    - name: set result
      set_fact:
        result: "no result"

  roles:
    - debug
    - test

